apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:3.9.11-eclipse-temurin-24-alpine
      command:
        - cat
      tty: true
      env:
      - name: NVD_API_KEY
        valueFrom:
          secretKeyRef:
            name: secret-credentials
            key: nvd-api-key
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        - mountPath: /tmp/trivycache/
          name: trivycache
    - name: trufflehog
      image: rmkanda/trufflehog
      command:
        - cat
      tty: true
    - name: licensefinder
      image: licensefinder/license_finder
      command:
        - cat
      tty: true
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      imagePullPolicy: Always
      env:
        - name: container
          value: docker
      command:
        - sleep
      args:
        - "99d"
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker
    - name: slscan
      image: shiftleft/sast-scan:latest
      imagePullPolicy: Always
      command:
        - cat
      tty: true
  volumes:
    - name: m2
      hostPath:
        path: /tmp/.m2/
    - name: docker-sock
      hostPath:
        path: /var/run
    - name: trivycache
      hostPath:
        path: /tmp/trivycache/
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: secret-credentials-dockerhub
              items:
                - key: .dockerconfigjson
                  path: config.json